### ISSUE TITLE
Returning false instead of throwing an error. (Also applies to the other bundles)

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCommonBundle#108]
Functions should return a value of a predefined format. Or an error.
Returning false to prevent throwing an error makes code more difficult to read.

ArrayTool::normalizeAndSerializeArray($configArray) for example should throw an error and not return false. This clearly indicates the consumer of the function that something went wrong. 

The consumer can then decide to do nothing (bubble the error), throw a custom error (or change the base error's message?), or pass to another strategy that handles cases that fail the normalize process.

**Comment by Davidmattei** [comment]
coding guideline
