### ISSUE TITLE
StfpStorage passwordPhrase forced to null

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCommonBundle#48]
Docblocks only allow null for the variable passwordPhrase. Is this legit? If so we could remove this completely as phpstan complains about passing null on line 89 to ssh2_auth_pubkey_file. If null we should pass nothing (fix coming up). 

But the question remains, should we remove this parameter completely as it is always null by the docs.

**Comment by theus77** [comment]
The $passwordPhrase allows null or string. This Issues can be closed
