### ISSUE TITLE
byPass should by bypass

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCommonBundle#57]
https://github.com/ems-project/EMSCommonBundle/blob/bb93a727a1d4a5e7b481e8c1806a31d9ab766f97/Logger/ElasticsearchLogger.php#L53

The byPass option disables the logging from elasticsearchlogger. In stead of "by pass" this should be "bypass", or better "disable" ?
However, I would prefer that the ElasticsearchLogger is not injected as a service if config disables logging.

**Comment by Davidmattei** [comment]
The elasticsearch logger is deprecated and already removed in the skeleton
